config/routes.rb
Rails.application.routes.draw do

  #【管理者用】
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #【会員用】
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root to: "public/homes#top"

  #【public/usersコントローラー】
  scope module: :public do
    get 'users/my_page' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/user_index' => 'users#user_index'
    delete 'users/destroy/:id' => 'users#destroy', as: 'destroy_user_post'
    get 'users/user_favorites' => 'users#user_favorites'
    # get 'users/myfavorites' => 'users#myfavorites'
  end

  #【public/postsコントローラー】
  scope module: :public do
    resources :posts, only:[:index, :new, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  #【admin/homesコントローラ】
  namespace :admin do
    get '/' => 'homes#top'
  end

  #【admin/usersコントローラー】
  namespace :admin do
     resources :users, only:[:index, :show, :edit, :update]
  end

   #【admin/postsコントローラー】
  namespace :admin do
     resources :posts, only:[:index, :show, :destroy]
  end

  #【admin/categoriesコントローラー】
  namespace :admin do
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @posts = Post.where(params[:user_id]).order(created_at: :desc)
   ##特定のユーザーに絞るのではなく、全ユーザーの投稿が表示されるようにparams[:user_id]だけを記述
    # @posts = Post.where(user_id: params[:user_id]).order(created_at: :desc)

    case params[:sort]
    when 'good'
      @posts = @posts.joins(:favorites).group(:post_id).order("count(post_id) desc").page(params[:page])
    when 'old'
      @posts = @posts.order(created_at: :asc).page(params[:page])
    else
      @posts = @posts.order(created_at: :desc).page(params[:page])
    end

    @categories = Category.all
    @comments = Comment.all
  end

  protected

  def post_params
    params.permit(:user_id, :category_id, :post_text, :image)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<!--<h4>admin/homes#top</h4>-->

<div class="ml-5">
  <%= notice %>
</div
<!--ログインの表示：確認済-->

<!--並び替えの切り替え土台-->
<%#= link_to '新着順', posts_path %>
<%#= link_to '古い順', posts_path(sort: 'old') %>
<%#= link_to 'いいね順', posts_path(sort: 'good') %>


<div class="container-fluid">
  <dic class="mt-2">

    <% @posts.each do |post| %>
      <div class="row mt-2">
        <div class="col-4 offset-4 border-bottom">
          <div class="row">
            <div class="col-4">
              <span style="font-size:13px;"><%=time_ago_in_words(post.created_at)%>前</span>
            </div>
            <div class="col-6">
              <%= link_to post.user.name, admin_user_path(post.user.id) %>
            </div>
          </div>
          <div class="row">
            <%= post.post_text %>
          </div>
          <div class="row">
            <div class="col-3">
              <span style="font-size:13px;">♥<%= post.favorites.count %> いいね</span>
            </div>
            <div class="col-4">
              <span style="font-size:13px;">
                コメント件数：<%= link_to post.comments.count, post_path(post.id) %>
              </span>
            </div>
          </div>
        </div>


        <div class="col-1 border-bottom">
          <% if post.image.attached? %>
            <%= image_tag post.image, size: "80x100" %>
          <%# else %>
            <%#= image_tag 'no-image.jpg', size: "70x90" %>
          <% end %>
        </div>
      </div>
    <% end %>


  </div>
</div>

<div class="mt-3">
  <%= paginate @posts %>
</div>