config/routes.rb
Rails.application.routes.draw do

  #【管理者用】
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #【会員用】
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root to: "public/homes#top"

  #【public/usersコントローラー】
  scope module: :public do
    get 'users/my_page' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/user_index' => 'users#user_index'
    delete 'users/destroy/:id' => 'users#destroy', as: 'destroy_user_post'
    get 'users/user_favorites' => 'users#user_favorites'
    # get 'users/myfavorites' => 'users#myfavorites'
  end

  #【public/postsコントローラー】
  scope module: :public do
    resources :posts, only:[:index, :new, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  #【admin/homesコントローラ】
  namespace :admin do
    get '/' => 'homes#top'
  end

  #【admin/usersコントローラー】
  namespace :admin do
     resources :users, only:[:index, :show, :edit, :update]
  end

   #【admin/postsコントローラー】
  namespace :admin do
     resources :posts, only:[:index, :show, :destroy]
  end

  #【admin/categoriesコントローラー】
  namespace :admin do
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  #post_category作成後、編集(複数選択出来るように中間テーブルを作成)
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  #※中間テーブルがあるときはt、Postがhrough:：(中間テーブル)を通して、categoryの情報を取りに行くイメージ
  #その際は、カテゴリーが紐付いた投稿は消さないように、dependentは記述しない。
  #このやり方で、カテゴリーは消えるが、それに紐付いた投稿は残るようになる。


  belongs_to :user

  #コメント機能
  has_many :comments, dependent: :destroy

  #いいね機能
  has_many :favorites, dependent: :destroy

  #この(user)にfavoritedされているかを確認するメソッド
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
    #特定のユーザーに絞る
    @posts = Post.where(user_id: params[:user_id]).order(created_at: :desc)
     #↑この一行だけだとエラー(NoMethodError in Admin::Posts#index　undefined method `user')が出たため追記
    @user = User.find(params[:user_id])

    case params[:sort]
    when 'good'
      @posts = @posts.left_joins(:favorites).group(:post_id).order("count(post_id) desc")
    when 'old'
      @posts = @posts.order(created_at: :asc)
    else
      @posts = @posts.order(created_at: :desc)
    end

    @categories = Category.all
    @comments = Comment.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    #コメントを投稿するためのインスタンス変数を定義
    @categories = Category.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path(user_id: params[:user_id])
  end


  protected

  def post_params
    params.permit(:user_id, :category_id, :post_text, :image)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<!--<h4>Admin::Posts#index</h4>-->

<div class="container-fluid">
  <dic class="mt-2">
    <div class="text-center">
      <h3><%= @user.name %>の投稿一覧</h3>
        <!--@userの前にPostをつけるとNoMethodError in Admin::Posts#index　undefined method `user'-->
        <!--コントローラーに@user = User.find(params[:user_id])追記-->
      </div>

 <% @posts.each do |post| %>
   <div class="row mt-2">
     <div class="col-5 offset-3 border-bottom">
        <div class="row">
          <div class="col-4">
            <span style="font-size:13px;"><%=time_ago_in_words(post.created_at)%>前</span>
          </div>
          <div class="col-6">
            <%= post.user.name %>
          </div>
        </div>
        <div class="row">
          <%= post.post_text %>
        </div>

        <div class="row mt-2">
          <div class="col-3">
            <% unless current_user.nil? %>
              <% if post.favorited_by?(current_user) %>
                  <%= link_to post_favorites_path(post), method: :delete do %>
                    <span style="font-size:13px;">♥<%= post.favorites.count %> いいね</span>
                  <% end %>
                <% else %>
                  <%= link_to post_favorites_path(post), method: :post do %>
                    <span style="font-size:13px;">♡<%= post.favorites.count %> いいね</span>
                  <% end %>
              <% end %>
            <% end %>

            <% if !current_user %>
              <span style="font-size:13px;">♥<%= post.favorites.count %> いいね</span>
            <% end %>
          </div>

          <div class="col-4">
            <span style="font-size:13px;">
              コメント件数：<%= link_to post.comments.count, post_path(post.id) %>
            </span>
          </div>

          <div class="col-4">
            <span style="font-size:13px;">
              <%= link_to "管理者用：削除", admin_post_path(post.id, user_id: params[:user_id]), method: :delete, "data-confirm" => "本当に削除しますか？" %>
            </span>
          </div>
        </div>
      </div>

      <div class="col-1 border-bottom">
        <% if post.image.attached? %>
          <%= image_tag post.image, size: "80x100" %>
        <%# else %>
          <%#= image_tag 'no-image.jpg', size: "70x70" %>
        <% end %>
      </div>
    </div>
  <% end %>

  </div>
</div>

app/views/admin/posts/show.html.erb
<h1>Admin::Posts#show</h1>
<p>Find me in app/views/admin/posts/show.html.erb</p>