config/routes.rb
Rails.application.routes.draw do

  #【管理者用】
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  #【会員用】
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root to: "public/homes#top"

  #【public/usersコントローラー】
  scope module: :public do
    get 'users/my_page' => 'users#show'
    get 'users/information/edit' => 'users#edit'
    patch 'users/information' => 'users#update'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/user_index' => 'users#user_index'
    delete 'users/destroy/:id' => 'users#destroy', as: 'destroy_user_post'
    get 'users/user_favorites' => 'users#user_favorites'
    # get 'users/myfavorites' => 'users#myfavorites'
  end

  #【public/postsコントローラー】
  scope module: :public do
    resources :posts, only:[:index, :new, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  #【admin/homesコントローラ】
  namespace :admin do
    get '/' => 'homes#top'
  end

  #【admin/usersコントローラー】
  namespace :admin do
     resources :users, only:[:index, :show, :edit, :update]
  end

   #【admin/postsコントローラー】
  namespace :admin do
     resources :posts, only:[:index, :show, :destroy]
  end

  #【admin/categoriesコントローラー】
  namespace :admin do
    resources :categories, only:[:index, :create, :edit, :update, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharehapi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Bootstrap導入のために、link_tagをpack_tagに書き換え-->
    <!--stylesheet_link_tagの場合cssファイルは、app/assets 配下のファイルを参照。
        stylesheet_pack_tagの場合は、app/javascript 配下のファイルを参照-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--ドロップダウンメニュー作成のために記述-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
<!--ここから上はもとから記述があった部分-->


 <body>
    <!--<header class="sticky-top" style="background-color: #ffb6c1;">-->
    <header class="sticky-top" style="background-color: white">
       <div class="container-fluid">
         <!--<div class="container-fluid">あとでこれに変えて調整するかも-->
          <!--<div class="heading">-->

          <!--<div class="container">-->
            <div class="row ml-2">
              <div class="col-auto mr-auto">
                <!--サイトのロゴ-->
                <% if admin_signed_in? %>
                  <%= link_to admin_path do %>
                    <%= image_tag('logo.jpg', size: "210x60") %>
                  <% end %>
                <% elsif user_signed_in? %>
                  <%= link_to posts_path do %>
                    <%= image_tag('logo.jpg', size: "210x60") %>
                  <% end %>
                <% else %>
                  <%= link_to root_path do %>
                    <%= image_tag('logo.jpg', size: "210x60") %>
                  <% end %>
                <% end %>
              </div>


              <!--<div class="col-auto">-->
              <!--管理者がログインした時-->

              <% if admin_signed_in? %>
                <div class="mt-3 mr-3">
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                    ログアウト <i class="fas fa-sign-out-alt"></i>
                  <% end %>
                </div>
                <!--顧客がログインしている時-->
                <% elsif user_signed_in? %>
                <div class="mt-3 mr-3">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    ログアウト <i class="fas fa-sign-out-alt"></i>
                  <% end %>
                </div>

              <!--管理者と顧客がログインしていない時-->
              <% else %>
                <div class="col-xs-4 ml-2">
                  <div class="mt-2 mr-3">
                    <%= link_to new_user_registration_path do %>
                      <i class="fas fa-pencil-alt"></i> 新規登録
                    <% end %>
                    <%= link_to new_user_session_path do %>
                      <i class="fas fa-sign-in-alt"></i> ユーザー:ログイン
                    <% end %>
                  </div>
                </div>
                <div class="col-xs-3 ml-2 mr-4 mt-2">
                  <%= link_to new_admin_session_path do %>
                    <i class="fas fa-lock"></i> 管理者:ログイン
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>


    <!--navbarの2段目、ドロップダウンメニュー-->

      <!--管理者がログインした時-->
      <% if admin_signed_in? %>
      <nav class="navbar sticky-top navbar-expand-lg navbar-light p-1" style="background-color: #bcddff;">
        <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
        <!--  <span class="navbar-toggler-icon"></span>-->
        <!--</button>-->


        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item">
              <!--<div class="mt-1">-->
                <font size="4"><strong>【 管理者画面 】</strong></font>
              <!--</div>-->
            </li>

            <li class="nav-item ml-5">
              <div class="mt-1">
                <%= link_to admin_users_path, class: "navbarlink" do %>
                  <i class="fas fa-users"></i> 会員一覧
                <% end %>
              </div>
              </a>
            </li>
            <li class="nav-item ml-5">
              <div class="mt-1 ml-4">
                <%= link_to admin_categories_path, class: "navbarlink" do %>
                  <i class="fas fa-folder-open"></i> カテゴリー関連
                <% end %>
              </a>
            </li>
            <li>
              <div class="mt-1 ml-5">
                 <i class="fas fa-heart"></i> <%= link_to "みんなの投稿", admin_path, class: "navbarlink" %>
              </div>
            </li>
          </ul>

        </div>
      </nav>


      <!--顧客がログインしている時-->
      <% elsif user_signed_in? %>
      <nav class="navbar sticky-top navbar-expand-lg navbar-light p-1" style="background-color: #ffccdc">
      <!--sticky-topは上部固定、p-1は高さ調整-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">

            <li class="nav-item">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <!--<i class="fas fa-user-cog">マイページ</i>-->
                <!--<font color="#ff0077">-->
                <font color="#ff1493"><i class="fas fa-user-cog"></i> マイページ</font>

              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item1"><%= link_to "my投稿一覧", users_user_index_path, class: "dropdown-item1" %></a>
                <a class="dropdown-item"><%= link_to "お気に入り一覧", users_user_favorites_path, class: "dropdown-item1" %></a>
                <a class="dropdown-item"><%= link_to "登録内容確認・編集", users_my_page_path, class: "dropdown-item1" %></a>
                <a class="dropdown-item"><%= link_to "退会手続", users_unsubscribe_path, class: "dropdown-item1" %></a>
              </div>
            </li>

            <!--<li class="nav-item">-->
            <!--  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
            <!--    <i class="fas fa-sort-amount-down"></i> 並び替え-->
            <!--  </a>-->

              <!--【public/posts#index】全ユーザーの投稿一覧-->
              <% if current_page?(posts_path) %>
              <!--今いるページが（〇〇_path）なら、下記のpathにとぶよ！という分岐-->
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"><%= link_to '新着順', posts_path() %></a>
                <a class="dropdown-item"><%= link_to '古い順', posts_path(sort: 'old') %></a>
                <a class="dropdown-item"><%= link_to 'いいね順', posts_path(sort: 'good') %></a>
              </div>

              <!--【public/users#user_index】-->
              <% elsif current_page?(users_user_index_path) %>
              <!--ここはelseのうしろに条件書きたいからelsif。elseでも大丈夫そうだけど…とメンターは言っていた-->
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"><%= link_to '新着順', users_user_index_path %></a>
                <a class="dropdown-item"><%= link_to '古い順', users_user_index_path(sort: 'old') %></a>
                <a class="dropdown-item"><%= link_to 'いいね順', users_user_index_path(sort: 'good') %></a>
              </div>
              <% end %>
            </li>

            <li class="nav-item ml-4">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <font color="#0095d9">
                  <i class="fas fa-folder-open"></i> カテゴリー検索
                </font>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <!--ここのカテゴリーはeach文で回して表示させる-->
                <% @categories.each do |category| %>
                  <a class="dropdown-item"><%= link_to category.name, posts_path(category_id: category.id) %></a>
                    <!--idを指定して取り出したい時は↑こういう書き方になる-->
                    <!--(genre_id: genre.id)これ書かないとエラー出る。-->
                    <!--genre_idで検索をかけて、その中(左側のgenre_id)からgenre.idというのを探す。数に例えると分かりやすい-->
                <% end %>
              </div>
            </li>
            <li>
              <div class="mt-2 ml-4">
                <font color="#00ac9b">
                  <i class="fas fa-heart"></i> <%= link_to "みんなの投稿", posts_path, class: "navbarlink1" %>
                </font>
              </div>
            </li>
            <li>
              <div class="mt-2 ml-5">
                <font color="#d9333f">
                  <i class="fas fa-edit"></i> <%= link_to "新規投稿", new_post_path, class: "navbarlink2" %>
                </font>
              </div>
            </li>

          </ul>

        </div>
      </nav>


      <!--管理者と顧客がログインしていない時-->
      <% else %>
        <nav class="navbar sticky-top  navbar-expand-lg navbar-light p-1" style="background-color: #ffccdc;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <!--<li class="nav-item">ここじゃなくて、public/home#topに貼り付けた-->
            <!--  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
            <!--    <i class="fas fa-sort-amount-down"></i> 並び替え-->
            <!--  </a>-->
            <!--  <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
            <!--    <a class="dropdown-item"><#= link_to '新着順', root_path %></a>-->
            <!--    <a class="dropdown-item"><%#= link_to '古い順', root_path(sort: 'old') %></a>-->
            <!--    <a class="dropdown-item"><%#= link_to 'いいね順', root_path(sort: 'good') %></a>-->
            <!--  </div>-->
            <!--</li>-->

            <div class="ml-5 mt-2">

              <p><font size="2">登録すると、投稿・コメント・各種マイページ機能が使えるよ ♪</font></p>

            </div>
          </ul>

        </div>
      </nav>

      <% end %>
        </div>
      </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html_forex_.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharehapi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Bootstrap導入のために、link_tagをpack_tagに書き換え-->
    <!--stylesheet_link_tagの場合cssファイルは、app/assets 配下のファイルを参照。
        stylesheet_pack_tagの場合は、app/javascript 配下のファイルを参照-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--ドロップダウンメニュー作成のために記述-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
<!--ここから上はもとから記述があった部分-->


 <body>
    <header>
      <div class="heading">
        <!--サイトのロゴ-->
        <% if user_signed_in? %>
          <%= link_to posts_path do %>
            <%= image_tag('no-image.jpg', size: "200x50") %>
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <%= image_tag('no-image.jpg', size: "200x50") %>
          <% end %>
        <% end %>
        <!--あとでadminの分も設定する-->


        <!--管理者がログインした時-->
        <% if admin_signed_in? %>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        <!--顧客がログインしている時-->
        <% elsif user_signed_in? %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <!--管理者と顧客がログインしていない時-->
        <% else %>
          <%= link_to "新規登録", new_user_registration_path %>
          <%= link_to "ユーザー：ログイン", new_user_session_path %>
          <%= link_to "管理者：ログイン", new_admin_session_path %>
        <% end %>

      </div>
    </header>

    <!--navbarの2段目、ドロップダウンメニュー-->

      <!--管理者がログインした時-->
      <% if admin_signed_in? %>
      <nav class="navbar navbar-icon-top navbar-expand-lg navbar-light" style="background-color: #ef857d;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item">
              <a class="nav-link" href="#">
                会員一覧
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">
                カテゴリー関連
              </a>
            </li>

          </ul>

        </div>
      </nav>


      <!--顧客がログインしている時-->
      <% elsif user_signed_in? %>
      <nav class="navbar navbar-icon-top navbar-expand-lg navbar-light" style="background-color: #ef857d;">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <!--<li class="nav-item">-->
            <!--  <a class="nav-link">-->
            <!--    <%#= link_to "Top", posts_path, class: "link" %>-->
            <!--  </a>-->
            <!--</li>-->

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                マイページ
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item"><%= link_to "my投稿一覧", users_user_index_path %></a>
                <a class="dropdown-item"><%= link_to "myいいね一覧", users_user_favorites_path %></a>
                <a class="dropdown-item"><%= link_to "登録内容確認・編集", users_my_page_path %></a>
                <a class="dropdown-item"><%= link_to "退会手続", users_unsubscribe_path %></a>
              </div>
            </li>

            <%= form_with url: posts_path, method: :get do |f| %>

               <%= f.select :sort, [['新着順', 'new'], ['古い順', "old"], ['いいね順', "good"]], include_blank: "選択して下さい", selected: params[:sort] %>
               <%= f.select :category_id, Category.pluck('name, id'), include_blank: "選択して下さい", selected: params[:category_id] %>

               <%= f.submit '送信'%>
            <% end %>
          </ul>


          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>

        </div>
      </nav>


      <!--管理者と顧客がログインしていない時-->
      <% else %>
        人気順
        カテゴリー
        検索窓
      <% end %>

    <!--nav-listの書き方参照する-->
    <!--  <ul class="nav-list">-->
    <!--    <li class="nav-list-item">-->
    <!--      <a href="index.html">Home</a>-->
    <!--    </li>-->
    <!--    <li class="nav-list-item">About</li>-->
    <!--    <li class="nav-list-item">Topic</li>-->
    <!--  </ul>-->
    <!--</nav>-->


    <%= yield %>
  </body>
</html>